<template>
  <div class="startStructure">
    <div class="startNavigation">


      <div>
        <div class="startNavigationIcons">
          <a href="">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-person-fill"
              viewBox="0 0 16 16">
              <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" />
            </svg>
          </a>
          <p>Profile</p>
        </div>

        <div class="startNavigationIcons">
          <a href="">
            <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="currentColor"
              class="bi bi-chat-text-fill" viewBox="0 0 16 16">
              <path
                d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM4.5 5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7zm0 2.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7zm0 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4z" />
            </svg>
          </a>
          <p>Chats</p>
        </div>
      </div>
      <div class="startLogOut">
        <button class="startBtnLogOut">Log out</button>
      </div>
    </div>


    <div class="startBase">

    </div>
  </div>
</template>
  
<script>

</script>
  
<style>
@import '../assets/css/start.css';
</style>